# Generated by Django 4.2.3 on 2023-07-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redactor',
            name='monthly_expenses',
            field=models.IntegerField(default=14675),
        ),
        migrations.AddField(
            model_name='redactor',
            name='monthly_income',
            field=models.IntegerField(default=17006),
        ),
        migrations.AddField(
            model_name='topic',
            name='competitiveness',
            field=models.TextField(default='ipsum'),
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(default='lorem'),
        ),
    ]
