# Generated by Django 4.2.3 on 2023-07-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_redactor_monthly_expenses_redactor_monthly_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redactor',
            name='monthly_expenses',
            field=models.IntegerField(default=3055),
        ),
        migrations.AlterField(
            model_name='redactor',
            name='monthly_income',
            field=models.IntegerField(default=10341),
        ),
        migrations.AlterField(
            model_name='topic',
            name='competitiveness',
            field=models.IntegerField(default=5),
        ),
    ]
