# Generated by Django 4.2.3 on 2023-07-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0003_alter_redactor_monthly_expenses_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redactor",
            name="monthly_expenses",
            field=models.IntegerField(default=11139),
        ),
        migrations.AlterField(
            model_name="redactor",
            name="monthly_income",
            field=models.IntegerField(default=3766),
        ),
    ]
